---

- name: Create shared folder
  file:
    path: "{{ ansible_env.HOME }}/{{ shared_folder }}"
    state: directory
    mode: "0777"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"

- name: Export folder
  become: true
  become_method: su
  lineinfile:
    path: /etc/exports
    line: "{{ ansible_env.HOME }}/{{ shared_folder }} *(rw,sync,no_subtree_check)"
    state: present
    insertafter: EOF

- name: Apply NFS export changes
  become: true
  become_method: su
  command: /usr/sbin/exportfs -a

- name: Reload NFS server service
  become: true
  become_method: su
  systemd:
    name: nfs-kernel-server
    state: restarted
    daemon_reload: yes

...
